import { LOCALES } from "@theme/configs/constsLocales";

const STATIC_CACHE_PAGE_NZ: string[] = [
    "/",
];

const STATIC_CACHE_PAGE_DE: string[] = [
    "/live/all",
    "/categories/table",
    "/categories/all",
    "/categories/new",
    "/categories/top",
    "/tournaments/all",
    "/categories/recommended",
];

const STATIC_CACHE_PAGE_AU: string[] = [
    "/pokies/megaways",
    "/pokies/pls-tournament",
    "/live/blackjack",
    "/live/roulette",
    "/live/baccarat",
    "/live/poker",
    "/live/game-shows",
    "/categories/all",
    "/categories/top",
    "/categories/recommended",
    "/tournaments/all",
    "/tournaments/lotteries",
    "/tournaments/actions",
    "/promotions",
    "/vip",
    "/about-btc",
    "/terms-and-conditions",
    "/privacy-policy",
    "/responsible-gaming",
    "/faq",
    "/bonus-terms-and-conditions",
    "/payments",
    "/producers/booongo",
    "/producers/playson",
    "/producers/igtech",
    "/producers/bgaming",
    "/producers/spinomenal",
    "/producers/wazdan",
    "/producers/yggdrasil",
    "/producers/luckystreak",
    "/producers/booming",
    "/producers/belatra",
    "/producers/bet2tech",
    "/producers/bsg",
    "/producers/felixgaming",
    "/producers/fugaso",
    "/producers/igrosoft",
    "/producers/kiron",
    "/producers/lucky",
    "/producers/mascot",
    "/producers/mrslotty",
    "/producers/nucleus",
    "/producers/platipus",
    "/producers/technology",
    "/producers/tomhorn",
    "/producers/truelab",
    "/producers/onlyplay",
    "/producers/spribe",
    "/producers/netgame",
    "/producers/gamebeat",
    "/producers/zillion",
    "/producers/atmosfera",
    "/producers/gamzix",
    "/producers/mancala",
    "/producers/swintt",
    "/producers/reevo",
    "/producers/avatarux",
    "/producers/1spin4win",
    "/producers/kagaming",
    "/producers/slotmill",
    "/producers/turbogames",
    "/producers/bluebird",
    "/producers/beterlive",
    "/producers/popiplay",
    "/play/igtech/monkeyking",
    "/play/igtech/wolftreasure",
    "/play/booongo/3coins",
    "/play/playson/buffalopowerholdandwin",
    "/play/booongo/sunofegypt3",
    "/play/booming/cashpig",
    "/play/bgaming/elvisfroginvegas",
    "/play/bgaming/aztecmagicbonanza",
    "/play/bgaming/alohakingelvis",
    "/play/wazdan/9coins",

    "/categories/new",
    "/categories/bonus-wagering",
    "/categories/jackpot",
    "/categories/btc-games",
    "/categories/table",
    "/tournaments",
    "/pokies/all",
    "/pokies/bonus-buy",
    "/live/all",
];

const STATIC_CACHE_PAGE_CA: string[] = [
    "/pokies/megaways",
    "/pokies/pls-tournament",
    "/live/baccarat",
    "/live/poker",
    "/live/game-shows",
    "/categories/top",
    "/categories/recommended",
    "/tournaments/lotteries",
    "/tournaments/all",
    "/tournaments/actions",
    "/promotions",
    "/vip",
    "/terms-and-conditions",
    "/privacy-policy",
    "/responsible-gaming",
    "/faq",
    "/about-btc",
    "/bonus-terms-and-conditions",
    "/payments",
    "/producers/booongo",
    "/producers/playson",
    "/producers/igtech",
    "/producers/bgaming",
    "/producers/spinomenal",
    "/producers/wazdan",
    "/producers/yggdrasil",
    "/producers/luckystreak",
    "/producers/booming",
    "/producers/belatra",
    "/producers/bet2tech",
    "/producers/bsg",
    "/producers/felixgaming",
    "/producers/fugaso",
    "/producers/igrosoft",
    "/producers/kiron",
    "/producers/lucky",
    "/producers/mascot",
    "/producers/mrslotty",
    "/producers/nucleus",
    "/producers/platipus",
    "/producers/technology",
    "/producers/tomhorn",
    "/producers/truelab",
    "/producers/onlyplay",
    "/producers/spribe",
    "/producers/netgame",
    "/producers/gamebeat",
    "/producers/zillion",
    "/producers/atmosfera",
    "/producers/gamzix",
    "/producers/mancala",
    "/producers/swintt",
    "/producers/reevo",
    "/producers/avatarux",
    "/producers/1spin4win",
    "/producers/kagaming",
    "/producers/slotmill",
    "/producers/turbogames",
    "/producers/bluebird",
    "/producers/beterlive",
    "/producers/popiplay",
    "/play/booongo/3coins",
    "/play/booming/cashpig",
    "/play/booming/burningclassics",
    "/play/bgaming/alohakingelvis",
    "/play/booming/howlingwolvesmegaways",

    "/categories/new",
    "/categories/bonus-wagering",
    "/categories/jackpot",
    "/categories/btc-games",
    "/categories/table",
    "/categories/all",
    "/pokies/all",
    "/pokies/bonus-buy",
    "/live/all",
    "/live/blackjack",
    "/live/roulette",
    "/tournaments",

];

export const STATIC_CACHE_PAGES_BY_LOCAL = {
    [LOCALES.CANADIAN_ENGLISH]: STATIC_CACHE_PAGE_CA,
    [LOCALES.AUSTRALIAN_ENGLISH]: STATIC_CACHE_PAGE_AU,
    [LOCALES.NEW_ZEALAND]: STATIC_CACHE_PAGE_NZ,
    [LOCALES.GERMANY]: STATIC_CACHE_PAGE_DE,

};
